# Default values for whoami.
# Source: https://github.com/cowboysysop/charts/blob/master/charts/whoami/values.yaml

## @param replicaCount Number of replicas
replicaCount: 1

image:
  ## @param image.repository Image repository
  repository: traefik/whoami

  ## @param image.tag Image tag
  tag: v1.10.2

## @param commonLabels Labels to add to all deployed objects
commonLabels: {}

ingress:
  ## @param ingress.enabled Enable ingress controller resource
  enabled: false

  ## @param ingress.ingressClassName IngressClass that will be be used to implement the Ingress
  ingressClassName: ""

  ## @param ingress.pathType Ingress path type
  pathType: ImplementationSpecific

  ## @param ingress.annotations Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  ## @param ingress.hosts[0].host Hostname to your Whoami installation
  ## @param ingress.hosts[0].paths Paths within the url structure
  hosts:
    - host: whoami.local
      paths:
        - /

  ## @param ingress.tls TLS configuration
  tls: []
    # - secretName: whoami-tls
    #   hosts:
    #     - whoami.local

